.TH "kvnatd" 8 "20 Nov 2002" "VNAT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kvnatd \- VNAT daemon. 
More...
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBkvnatd\fP"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
VNAT daemon.
.PP
VNAT daemon (kvnatd) is a kernel daemon process that implements the VNAT Connection Migration Protocol (VCMP) for negotiating various options (e.g., suspension time, helper, security, etc.) at suspending time and for updating virtual-physical address mapping at resuming time.
.PP
Kvnatd is not started from a command line. It is created when the VNAT module is loaded and killed when the VNAT module is unloaded.
.PP
Copyright (c) 2001-2002 Gong Su, All rights reserved.
.PP
See the file 'COPYRIGHT' for information on usage and redistribution of this file. 
